devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Stdin
    channels: 2
    format: F32_LE
  playback:
    type: PipeWire
    channels: 2
    autoconnect_to: ""

filters: {}

pipeline: []
