devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Stdin
    channels: 2
    format: F32_LE
  playback:
    type: PipeWire
    channels: 2

filters:
  bass_boost:
    type: Biquad
    parameters:
      type: Lowshelf
      freq: 100
      gain: 4
      q: 0.7

pipeline:
  - type: Filter
    channels: [0, 1]
    names:
      - bass_boost
